# Define the port on which your service listens for requests
port: 8000

# Reference the endpoints file for detailed endpoint configurations
endpoints:
  # Path to your endpoints file (relative to the component-config.yaml location)
  file: ./endpoints.yaml

# Optional: Additional configurations specific to your service (if any)
# ... (refer to Choreo documentation for specific options)
