# Generated by Django 4.0.4 on 2024-06-05 16:23

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('stockwhisper', '0002_rename_symbol_stock_ticker'),
    ]

    operations = [
        migrations.AddField(
            model_name='stock',
            name='period',
            field=models.CharField(blank=True, max_length=10),
        ),
    ]
