# Generated by Django 4.0.4 on 2024-06-06 07:31

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('stockwhisper', '0004_alter_stock_ticker'),
    ]

    operations = [
        migrations.AlterField(
            model_name='stock',
            name='period',
            field=models.CharField(default='5d', max_length=10),
        ),
    ]
