# Generated by Django 5.0.6 on 2024-06-06 12:07

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('stockwhisper', '0005_alter_stock_period'),
    ]

    operations = [
        migrations.AlterField(
            model_name='stock',
            name='period',
            field=models.CharField(max_length=10),
        ),
    ]
