# Generated by Django 5.0.6 on 2024-06-06 13:29

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('stockwhisper', '0007_alter_stock_company_name'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='stock',
            name='historical_data',
        ),
        migrations.AddField(
            model_name='stock',
            name='change',
            field=models.DecimalField(decimal_places=2, max_digits=10, null=True),
        ),
    ]
