# Generated by Django 5.0.6 on 2024-06-08 12:07

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('stockwhisper', '0008_remove_stock_historical_data_stock_change'),
    ]

    operations = [
        migrations.AddField(
            model_name='stock',
            name='history_data',
            field=models.JSONField(blank=True, default='{}'),
        ),
    ]
